name: SCOUT 🚨

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  scout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout SCOUT
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run SCOUT
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python scout.py
